# Generated by Django 4.2.11 on 2024-11-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alummno',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
