# Generated by Django 4.2.11 on 2024-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0003_estudianteprimaria_estudiantesecundaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alummno',
        ),
        migrations.AddField(
            model_name='estudianteprimaria',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=150),
        ),
        migrations.AddField(
            model_name='estudianteprimaria',
            name='edad',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='estudianteprimaria',
            name='nombre',
            field=models.CharField(default='nombre', max_length=150),
        ),
        migrations.AddField(
            model_name='estudianteprimaria',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='estudianteprimaria',
            name='telefono',
            field=models.CharField(blank=True, default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='estudiantesecundaria',
            name='apellido',
            field=models.CharField(default='Apellido', max_length=150),
        ),
        migrations.AddField(
            model_name='estudiantesecundaria',
            name='edad',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='estudiantesecundaria',
            name='nombre',
            field=models.CharField(default='nombre', max_length=150),
        ),
        migrations.AddField(
            model_name='estudiantesecundaria',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='estudiantesecundaria',
            name='telefono',
            field=models.CharField(blank=True, default='0000000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='etapa',
            field=models.CharField(choices=[('primaria', 'Primaria')], default='primaria', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='grado',
            field=models.CharField(blank=True, default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='jornada',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], default='mañana', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='etapa',
            field=models.CharField(choices=[('secundaria', 'Secundaria')], default='secundaria', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='grado',
            field=models.CharField(blank=True, default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='jornada',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], default='mañana', max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='media',
            field=models.BooleanField(default=False, help_text='Indica si el estudiante está en media académica (grados 10 y 11)'),
        ),
    ]
