# Generated by Django 4.2.11 on 2024-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_alummno_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantePrimaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=10)),
                ('jornada', models.CharField(choices=[('mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10)),
                ('pae', models.BooleanField(default=False)),
                ('transporte', models.BooleanField(default=False)),
                ('etapa', models.CharField(choices=[('primaria', 'Primaria')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstudianteSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=10)),
                ('jornada', models.CharField(choices=[('mañana', 'Mañana'), ('Tarde', 'Tarde')], max_length=10)),
                ('pae', models.BooleanField(default=False)),
                ('transporte', models.BooleanField(default=False)),
                ('media', models.BooleanField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('secundaria', 'Secundaria')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alummno',
            name='etapa',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='alummno',
            name='grado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='alummno',
            name='jornada',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='alummno',
            name='pae',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alummno',
            name='transporte',
            field=models.BooleanField(default=False),
        ),
    ]
