# Generated by Django 4.2.11 on 2024-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0004_delete_alummno_estudianteprimaria_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='grado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='jornada',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='grado',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='jornada',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
