# Generated by Django 4.2.11 on 2024-11-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0005_alter_estudianteprimaria_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='apellido',
            new_name='_apellido',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='edad',
            new_name='_edad',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='grado',
            new_name='_grado',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='jornada',
            new_name='_jornada',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='nombre',
            new_name='_nombre',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='transporte',
            new_name='_pae',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='sexo',
            new_name='_sexo',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='telefono',
            new_name='_telefono',
        ),
        migrations.RenameField(
            model_name='estudianteprimaria',
            old_name='pae',
            new_name='_transporte',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='apellido',
            new_name='_apellido',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='edad',
            new_name='_edad',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='grado',
            new_name='_grado',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='jornada',
            new_name='_jornada',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='nombre',
            new_name='_nombre',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='pae',
            new_name='_pae',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='sexo',
            new_name='_sexo',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='telefono',
            new_name='_telefono',
        ),
        migrations.RenameField(
            model_name='estudiantesecundaria',
            old_name='transporte',
            new_name='_transporte',
        ),
    ]
