# Generated by Django 5.1.3 on 2024-11-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0006_rename_apellido_estudianteprimaria__apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudianteprimaria',
            name='_grado',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Undécimo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='_grado',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Séptimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Décimo'), ('11', 'Undécimo')], max_length=10),
        ),
    ]
