# Generated by Django 5.1.3 on 2024-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0009_remove_estudiantesecundaria_tipo_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantesecundaria',
            name='tipo_de_media',
            field=models.CharField(blank=True, help_text='Nombre de la media en la cual está estudiando, si aplica.', max_length=20),
        ),
    ]
